### ISSUE TITLE
开发版的细节错误

### ISSUE THREAD

**Issue by NatsumiXD** [HCAT-Project/re_hcat-server#17]
`FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'plugins'`(没有开局mkdir
`ModuleNotFoundError: No module named 'pysnooper'`：依赖出了点问题（

**Comment by hsn8086** [comment]
@NatsumiXD uh...删掉那行就行
这个是测试用的包
或者你安装个pysnooper也行

**Comment by hsn8086** [comment]
应该删干净了..?
