### ISSUE TITLE
Windows下的client错误

### ISSUE THREAD

**Issue by NatsumiXD** [HCAT-Project/re_hcat-server#18]
直接把自己给覆盖掉了.....

**Comment by NatsumiXD** [comment]
![image](https://github.com/HCAT-Project/re_hcat-server/assets/63963655/c89fb160-253e-4b31-ad3b-bef283a0cb57)

**Comment by NatsumiXD** [comment]
有点危险啊啊啊啊啊啊

**Comment by hsn8086** [comment]
目前没搞清楚什么原因...等等去win那台试试..

**Comment by hsn8086** [comment]
大概明白了...不知是subprocess的cwd设置的问题还是git的问题...烦死了,看看怎么修吧...

**Comment by hsn8086** [comment]
fixed.
